name: 🔗 Webhooks & Sincronização

on:
  push:
    branches: [ main, develop ]
  deployment_status:
  repository_dispatch:
    types: [webhook-trigger, sync-request]
  workflow_dispatch:
    inputs:
      sync_type:
        description: 'Tipo de sincronização'
        required: true
        default: 'full'
        type: choice
        options:
        - full
        - partial
        - metadata

env:
  WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}

jobs:
  # 🔄 Sincronização de Deploy
  deploy-sync:
    name: 🔄 Deploy Sync
    runs-on: ubuntu-latest
    if: github.event_name == 'deployment_status'
    
    steps:
    - name: 📡 Webhook Deploy Status
      run: |
        echo "Deploy Status: ${{ github.event.deployment_status.state }}"
        echo "Environment: ${{ github.event.deployment_status.environment }}"
        echo "URL: ${{ github.event.deployment_status.target_url }}"

    - name: 🌐 Notify External Services
      run: |
        # Notificar serviços externos sobre deploy
        curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d "{
            \"text\": \"🚀 Deploy realizado no ambiente **${{ github.event.deployment_status.environment }}**\",
            \"attachments\": [{
              \"color\": \"${{ github.event.deployment_status.state == 'success' && 'good' || 'danger' }}\",
              \"fields\": [{
                \"title\": \"Status\",
                \"value\": \"${{ github.event.deployment_status.state }}\",
                \"short\": true
              }, {
                \"title\": \"URL\",
                \"value\": \"${{ github.event.deployment_status.target_url }}\",
                \"short\": true
              }]
            }]
          }" || echo "Slack webhook não configurado"

    - name: 📊 Update Metrics
      run: |
        # Atualizar métricas de deploy
        echo "Updating deployment metrics..."
        echo "Deploy Count: $(date +%s)" > deployment_metrics.json

  # 🔗 Processamento de Webhooks
  webhook-processor:
    name: 🔗 Webhook Processor
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch'
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 🔍 Process Webhook Data
      id: process
      run: |
        echo "Event Type: ${{ github.event.action }}"
        echo "Client Payload: ${{ toJson(github.event.client_payload) }}"
        
        # Processar diferentes tipos de webhook
        case "${{ github.event.action }}" in
          "webhook-trigger")
            echo "webhook_type=external" >> $GITHUB_OUTPUT
            ;;
          "sync-request")
            echo "webhook_type=sync" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "webhook_type=unknown" >> $GITHUB_OUTPUT
            ;;
        esac

    - name: 🔄 External Webhook Handler
      if: steps.process.outputs.webhook_type == 'external'
      run: |
        echo "Processing external webhook..."
        # Processar webhook de serviços externos (Discord, Slack, etc.)
        
        # Exemplo: Discord webhook
        if [[ -n "${{ secrets.DISCORD_WEBHOOK }}" ]]; then
          curl -H "Content-Type: application/json" \
               -d "{\"content\":\"📡 Webhook recebido: ${{ toJson(github.event.client_payload) }}\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
        fi

    - name: 🔄 Sync Request Handler
      if: steps.process.outputs.webhook_type == 'sync'
      run: |
        echo "Processing sync request..."
        # Sincronizar dados com APIs externas
        
        # Exemplo: Sincronizar com banco de dados
        curl -X POST https://api.l3trament0.com/sync \
          -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{
            \"repository\": \"${{ github.repository }}\",
            \"branch\": \"${{ github.ref_name }}\",
            \"commit\": \"${{ github.sha }}\",
            \"timestamp\": \"$(date -Iseconds)\"
          }" || echo "API sync failed"

  # 📡 Monitoramento de Uptime
  uptime-monitor:
    name: 📡 Uptime Monitor
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    
    steps:
    - name: 🌐 Check Production Sites
      id: uptime
      run: |
        # Verificar status dos sites
        VERCEL_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://l3trament0web3.vercel.app || echo "000")
        NETLIFY_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://l3trament0web3.netlify.app || echo "000")
        GITHUB_PAGES_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://catitodev.github.io/l3trament0web3 || echo "000")
        
        echo "vercel_status=$VERCEL_STATUS" >> $GITHUB_OUTPUT
        echo "netlify_status=$NETLIFY_STATUS" >> $GITHUB_OUTPUT
        echo "github_pages_status=$GITHUB_PAGES_STATUS" >> $GITHUB_OUTPUT

    - name: 🚨 Alert on Down Sites
      if: steps.uptime.outputs.vercel_status != '200' || steps.uptime.outputs.netlify_status != '200'
      run: |
        # Alertar sobre sites fora do ar
        MESSAGE="🚨 **ALERTA**: Alguns sites estão fora do ar!
        
        - Vercel: ${{ steps.uptime.outputs.vercel_status == '200' && '✅' || '❌' }} (${{ steps.uptime.outputs.vercel_status }})
        - Netlify: ${{ steps.uptime.outputs.netlify_status == '200' && '✅' || '❌' }} (${{ steps.uptime.outputs.netlify_status }})
        - GitHub Pages: ${{ steps.uptime.outputs.github_pages_status == '200' && '✅' || '❌' }} (${{ steps.uptime.outputs.github_pages_status }})
        
        Timestamp: $(date)"
        
        # Discord alert
        if [[ -n "${{ secrets.DISCORD_WEBHOOK }}" ]]; then
          curl -H "Content-Type: application/json" \
               -d "{\"content\":\"$MESSAGE\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
        fi

    - name: 📊 Update Status Page
      run: |
        # Atualizar página de status
        cat > status.json << EOF
        {
          "timestamp": "$(date -Iseconds)",
          "services": {
            "vercel": {
              "status": "${{ steps.uptime.outputs.vercel_status }}",
              "healthy": ${{ steps.uptime.outputs.vercel_status == '200' && 'true' || 'false' }}
            },
            "netlify": {
              "status": "${{ steps.uptime.outputs.netlify_status }}",
              "healthy": ${{ steps.uptime.outputs.netlify_status == '200' && 'true' || 'false' }}
            },
            "github_pages": {
              "status": "${{ steps.uptime.outputs.github_pages_status }}",
              "healthy": ${{ steps.uptime.outputs.github_pages_status == '200' && 'true' || 'false' }}
            }
          }
        }
        EOF

  # 🔄 Backup Automático
  auto-backup:
    name: 🔄 Backup Automático
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 📦 Create Backup
      run: |
        # Criar backup do repositório
        BACKUP_NAME="l3trament0web3-backup-$(date +%Y%m%d-%H%M%S)"
        
        # Criar bundle Git
        git bundle create ${BACKUP_NAME}.bundle --all
        
        # Criar tar.gz do código fonte
        tar -czf ${BACKUP_NAME}-source.tar.gz \
          --exclude=node_modules \
          --exclude=.git \
          --exclude=dist \
          .

    - name: ☁️ Upload to Cloud Storage
      run: |
        # Upload para cloud storage (exemplo com curl)
        echo "Uploading backup to cloud storage..."
        
        # Simular upload (substitua pela API real)
        curl -X POST https://backup-api.example.com/upload \
          -H "Authorization: Bearer ${{ secrets.BACKUP_TOKEN }}" \
          -F "file=@l3trament0web3-backup-$(date +%Y%m%d-%H%M%S).bundle" \
          || echo "Backup upload failed"

  # 🔔 Sistema de Notificações
  notification-system:
    name: 🔔 Notificações
    runs-on: ubuntu-latest
    needs: [deploy-sync, webhook-processor, uptime-monitor]
    if: always()
    
    steps:
    - name: 📊 Generate Status Report
      run: |
        echo "## 📊 Relatório de Sincronização" >> $GITHUB_STEP_SUMMARY
        echo "- **Deploy Sync**: ${{ needs.deploy-sync.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Webhook Processor**: ${{ needs.webhook-processor.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Uptime Monitor**: ${{ needs.uptime-monitor.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Timestamp**: $(date)" >> $GITHUB_STEP_SUMMARY

    - name: 🌐 Send Notifications
      run: |
        # Enviar notificações para múltiplos canais
        SUMMARY="🔗 **Sincronização L3trament0Web3**
        
        Status dos serviços:
        - Deploy Sync: ${{ needs.deploy-sync.result }}
        - Webhooks: ${{ needs.webhook-processor.result }}
        - Monitoramento: ${{ needs.uptime-monitor.result }}
        
        $(date)"
        
        # Discord
        if [[ -n "${{ secrets.DISCORD_WEBHOOK }}" ]]; then
          curl -H "Content-Type: application/json" \
               -d "{\"content\":\"$SUMMARY\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
        fi
        
        # Telegram
        if [[ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]] && [[ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]]; then
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
               -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$SUMMARY"
        fi